# services/nginx.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-app
spec:
  type: LoadBalancer 
  selector:
    app: nginx  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
